**Задача1**

Напишите функцию, которая классифицирует фильмы из материалов занятия по следующим правилам:
- оценка 2 и меньше - низкий рейтинг
- оценка 4 и меньше - средний рейтинг
- оценка 4.5 и 5 - высокий рейтинг

Результат классификации запишите в столбец class

***Решение***

In [2]:
import pandas as pd

ratings = pd.read_csv('ml-latest-small/ratings.csv')

def rates(row):
    if row['rating'] <= 2:
        return 'low rate'
    elif 2 < row['rating'] <= 4:
        return 'middle rate'
    elif 4.5 <= row['rating'] <= 5:
        return 'high rate'

ratings['class'] = ratings.apply(rates, axis=1)
ratings.head()

   userId  movieId  rating   timestamp        class
0       1       31     2.5  1260759144  middle rate
1       1     1029     3.0  1260759179  middle rate
2       1     1061     3.0  1260759182  middle rate
3       1     1129     2.0  1260759185     low rate
4       1     1172     4.0  1260759205  middle rate

**Задача2**

Используем файл keywords.csv.

Необходимо написать гео-классификатор, который каждой строке сможет выставить географическую принадлежность определенному региону. Т. е. если поисковый запрос содержит название города региона, то в столбце ‘region’ пишется название этого региона. Если поисковый запрос не содержит названия города, то ставим ‘undefined’.

Правила распределения по регионам Центр, Северо-Запад и Дальний Восток:

geo_data = {

'Центр': ['москва', 'тула', 'ярославль'],

'Северо-Запад': ['петербург', 'псков', 'мурманск'],

'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']
}

Результат классификации запишите в отдельный столбец region.

***Решение***

In [25]:
keywords.head(10)

                      keyword     shows
0                          вк  64292779
1               одноклассники  63810309
2                       порно  41747114
3                        ютуб  39995567
4                   вконтакте  21014195
5  одноклассники моя страница  19976138
6                        майл  15144673
7                       авито  14786593
8                  переводчик  14453469
9                      яндекс  13344734

In [4]:
geo_data = {
'Центр': ['москва', 'тула', 'ярославль'],
'Северо-Запад': ['петербург', 'псков', 'мурманск', 'одноклассники'], #одноклассники для теста
'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск', 'вконтакте'] #вконтакте для теста
}

In [5]:
keywords = pd.read_csv('keywords.csv')

def geo(keyword):
    
    # проходим по ключам (название региона) и значениям (список городов региона) словаря geo_data
    for region, city_list in geo_data.items():
        # проходим по каждому городу региона
        for city in city_list:
            # если название города есть в поисковом запросе, то возвращаем название региона region
            if city in keyword:
                return region
    
    # если ничего не нашлось, то возвращаем undefined
    return 'undefined'

keywords['region'] = keywords.apply(geo, axis=1)
keywords.head(15)

                       keyword     shows     region
0                           вк  64292779  undefined
1                одноклассники  63810309  undefined
2                        порно  41747114  undefined
3                         ютуб  39995567  undefined
4                    вконтакте  21014195  undefined
5   одноклассники моя страница  19976138  undefined
6                         майл  15144673  undefined
7                        авито  14786593  undefined
8                   переводчик  14453469  undefined
9                       яндекс  13344734  undefined
10             сбербанк онлайн  10725673  undefined
11                        mail   7687204  undefined
12                        игры   6075762  undefined
13                     youtube   5729958  undefined
14      вконтакте моя страница   5971451  undefined